# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ykea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id_bill', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itemquantity',
            fields=[
                ('id_itemquantity', models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('amountItem', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Linebill',
            fields=[
                ('id_linebill', models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bill', to='ykea.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id_shoppingcart', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='featured_photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.FileField(upload_to='instructions'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(through='ykea.Itemquantity', to='ykea.Item'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ykea.Customer'),
        ),
        migrations.AddField(
            model_name='linebill',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Item'),
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Item'),
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='shoppingcart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Shoppingcart'),
        ),
        migrations.AddField(
            model_name='bill',
            name='linebill',
            field=models.ManyToManyField(through='ykea.Linebill', to='ykea.Item'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='ykea.Customer'),
        ),
    ]
