# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 01:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ykea', '0002_auto_20180512_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id_bill', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itemquantity',
            fields=[
                ('id_itemquantity', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('amountItem', models.CharField(max_length=3)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Linebill',
            fields=[
                ('id_linebill', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.CharField(max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bill', to='ykea.Bill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='intermediate',
            name='item',
        ),
        migrations.RemoveField(
            model_name='intermediate',
            name='shoppingcart',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='id',
            new_name='id_shoppingcart',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(through='ykea.Itemquantity', to='ykea.Item'),
        ),
        migrations.DeleteModel(
            name='Intermediate',
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='shoppingcart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Shoppingcart'),
        ),
        migrations.AddField(
            model_name='bill',
            name='linebill',
            field=models.ManyToManyField(through='ykea.Linebill', to='ykea.Item'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='ykea.Customer'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ykea.Customer'),
        ),
    ]
