# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0003_auto_20180518_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.FileField(upload_to='instructions'),
        ),
    ]
