# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0004_auto_20180518_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_customer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
